apiVersion: v1
kind: ServiceAccount
metadata:
  name: cdo-correlator-worker
  namespace: tf1-aiops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    eks.amazonaws.com/role-arn: arn:aws:iam::022267198114:role/tf1-correlator-worker-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-engine
  namespace: ai-engine
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    eks.amazonaws.com/role-arn: arn:aws:iam::022267198114:role/tf1-ai-engine-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  namespace: tf1-aiops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-role-binding
  namespace: tf1-aiops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
  - kind: Group
    name: "triage-hub-developers"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sre-cluster-role
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods/portforward", "pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sre-role-binding
  namespace: tf1-aiops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
  - kind: Group
    name: "triage-hub-sre"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: sre-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: correlator-worker-k8s-role
  namespace: tf1-aiops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: correlator-worker-k8s-binding
  namespace: tf1-aiops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
  - kind: ServiceAccount
    name: cdo-correlator-worker
    namespace: tf1-aiops
roleRef:
  kind: Role
  name: correlator-worker-k8s-role
  apiGroup: rbac.authorization.k8s.io
