apiVersion: v1
kind: Service
metadata:
  name: ai-engine-service
  namespace: ai-engine
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: ai-engine
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
